#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Dec 13 11:49:38 2018

@author: MikkelGronning
"""

[ls, datasets] = my_f.loadHDF5_File("preprocced_data/2016_11_02.h5")
u = 33000
v = 34100


data = datasets[3][u:v]


tmp = detection(data, windowsize=150, epsilon = 0.25, delta=0.01, MinToCompare = 30, progress = False)